:targets:
- :name:
  :type:     redshift
  :host:
  :database:
  :port:
  :username:
  :password:
  :ssl:
:variables:
  :input_schema:       atomic
  :scratch_schema:     scratch
  :output_schema:      derived
  :entropy:            ""
:steps:
- :name: 99-indicative-export-cleanup
  :queries:
    - :name: 99-indicative-export-cleanup
      :file: custom/01-indicative-export/99-indicative-export-cleanup.sql
      :template: true
