-- 1. Create prod table

CREATE TABLE IF NOT EXISTS {{.output_schema}}.indicative_export{{.entropy}} (
(
  app_id                      VARCHAR(255) ENCODE ZSTD,
  br_family                   VARCHAR(50) ENCODE ZSTD,
  br_features_director        BOOLEAN ENCODE ZSTD,
  br_features_flash           BOOLEAN ENCODE ZSTD,
  br_features_gears           BOOLEAN ENCODE ZSTD,
  br_features_java            BOOLEAN ENCODE ZSTD,
  br_features_pdf             BOOLEAN ENCODE ZSTD,
  br_features_quicktime       BOOLEAN ENCODE ZSTD,
  br_features_realplayer      BOOLEAN ENCODE ZSTD,
  br_features_silverlight     BOOLEAN ENCODE ZSTD,
  br_features_windowsmedia    BOOLEAN ENCODE ZSTD,
  br_lang                     VARCHAR(255) ENCODE ZSTD,
  br_name                     VARCHAR(50) ENCODE ZSTD,
  br_renderengine             VARCHAR(50) ENCODE ZSTD,
  br_type                     VARCHAR(50) ENCODE ZSTD,
  br_version                  VARCHAR(50) ENCODE ZSTD,
  br_viewheight               INT ENCODE ZSTD,
  br_viewwidth                INT ENCODE ZSTD,
  doc_height                  INT ENCODE ZSTD,
  doc_width                   INT ENCODE ZSTD,
  domain_sessionid            CHARACTER ENCODE ZSTD,
  domain_sessionidx           INT ENCODE ZSTD,
  domain_userid               VARCHAR(128) ENCODE ZSTD,
  dvce_ismobile               BOOLEAN ENCODE ZSTD,
  dvce_screenheight           INT ENCODE ZSTD,
  dvce_screenwidth            INT ENCODE ZSTD,
  dvce_type                   VARCHAR(50) ENCODE ZSTD,
  event                       VARCHAR(128) ENCODE ZSTD,
  event_id                    CHAR(36) NOT NULL UNIQUE ENCODE ZSTD,
  event_vendor                VARCHAR(1000) ENCODE ZSTD,
  geo_city                    VARCHAR(75) ENCODE ZSTD,
  geo_country                 CHAR(2) ENCODE ZSTD,
  geo_region                  CHAR(3) ENCODE ZSTD,
  geo_region_name             VARCHAR(100) ENCODE ZSTD,
  geo_timezone                VARCHAR(64) ENCODE ZSTD,
  geo_zipcode                 VARCHAR(15) ENCODE ZSTD,
  mkt_campaign                VARCHAR(255) ENCODE ZSTD,
  mkt_clickid                 VARCHAR(128) ENCODE ZSTD,
  mkt_content                 VARCHAR(500) ENCODE ZSTD,
  mkt_medium                  VARCHAR(255) ENCODE ZSTD,
  mkt_network                 VARCHAR(64) ENCODE ZSTD,
  mkt_source                  VARCHAR(255) ENCODE ZSTD,
  mkt_term                    VARCHAR(255) ENCODE ZSTD,
  network_userid              VARCHAR(128) ENCODE ZSTD,
  os_family                   VARCHAR(50) ENCODE ZSTD,
  os_manufacturer             VARCHAR(50) ENCODE ZSTD,
  os_name                     VARCHAR(50) ENCODE ZSTD,
  os_timezone                 VARCHAR(255) ENCODE ZSTD,
  page_referrer               VARCHAR(4096) ENCODE ZSTD,
  page_title                  VARCHAR(2000) ENCODE ZSTD,
  page_url                    VARCHAR(4096) ENCODE ZSTD,
  page_urlfragment            VARCHAR(3000) ENCODE ZSTD,
  page_urlhost                VARCHAR(255) ENCODE ZSTD,
  page_urlpath                VARCHAR(3000) ENCODE ZSTD,
  page_urlquery               VARCHAR(6000) ENCODE ZSTD,
  platform                    VARCHAR(255) ENCODE ZSTD,
  refr_domain_userid          VARCHAR(128) ENCODE ZSTD,
  refr_medium                 VARCHAR(25) ENCODE ZSTD,
  refr_source                 VARCHAR(50) ENCODE ZSTD,
  refr_term                   VARCHAR(255) ENCODE ZSTD,
  refr_urlfragment            VARCHAR(3000) ENCODE ZSTD,
  refr_urlhost                VARCHAR(255) ENCODE ZSTD,
  refr_urlpath                VARCHAR(6000) ENCODE ZSTD,
  refr_urlquery               VARCHAR(6000) ENCODE ZSTD,
  se_action                   VARCHAR(1000) ENCODE ZSTD,
  se_category                 VARCHAR(1000) ENCODE ZSTD,
  se_label                    VARCHAR(4096) ENCODE ZSTD,
  se_property                 VARCHAR(1000) ENCODE ZSTD,
  se_value                    DOUBLE PRECISION ENCODE ZSTD,
  ti_category                 VARCHAR(255) ENCODE ZSTD,
  ti_currency                 CHAR(3) ENCODE ZSTD,
  ti_name                     VARCHAR(255) ENCODE ZSTD,
  ti_orderid                  VARCHAR(255) ENCODE ZSTD,
  ti_price                    DECIMAL(18,2) ENCODE ZSTD,
  ti_price_base               DECIMAL(18,2) ENCODE ZSTD,
  ti_quantity                 INT ENCODE ZSTD,
  ti_sku                      VARCHAR(255) ENCODE ZSTD,
  tr_affiliation              VARCHAR(255) ENCODE ZSTD,
  tr_city                     VARCHAR(255) ENCODE ZSTD,
  tr_country                  VARCHAR(255) ENCODE ZSTD,
  tr_currency                 CHAR(3) ENCODE ZSTD,
  tr_orderid                  VARCHAR(255) ENCODE ZSTD,
  tr_shipping                 DECIMAL(18,2) ENCODE ZSTD,
  tr_shipping_base            DECIMAL(18,2) ENCODE ZSTD,
  tr_state                    VARCHAR(255) ENCODE ZSTD,
  tr_tax                      DECIMAL(18,2) ENCODE ZSTD,
  tr_tax_base                 DECIMAL(18,2) ENCODE ZSTD,
  tr_total                    DECIMAL(18,2) ENCODE ZSTD,
  tr_total_base               DECIMAL(18,2) ENCODE ZSTD,
  user_fingerprint            VARCHAR(128) ENCODE ZSTD,
  user_id                     VARCHAR(255) ENCODE ZSTD,
  user_ipaddress              VARCHAR(128) ENCODE ZSTD,
  useragent                   VARCHAR(1000) ENCODE ZSTD,
  collector_tstamp            TIMESTAMP NOT NULL ENCODE RAW,
  event_name                  VARCHAR(1000) ENCODE ZSTD,
  custom_event_name           VARCHAR(1000) ENCODE ZSTD,
  derived_tstamp              TIMESTAMP ENCODE ZSTD,
  change_form_form_id         VARCHAR(255) ENCODE ZSTD,
  change_form_element_id      VARCHAR(255) ENCODE ZSTD,
  change_form_node_name       VARCHAR(8) ENCODE ZSTD,
  change_form_element_classes VARCHAR(5000) ENCODE ZSTD,
  submit_form_form_id         VARCHAR(255) ENCODE ZSTD,
  submit_form_form_classes    VARCHAR(2048) ENCODE ZSTD,
  submit_form_elements        VARCHAR(4096) ENCODE ZSTD,
  link_click_element_id       VARCHAR(255) ENCODE ZSTD,
  link_click_element_classes  VARCHAR(2048) ENCODE ZSTD,
  link_click_element_target   VARCHAR(255) ENCODE ZSTD,
  link_click_target_url       VARCHAR(4096) ENCODE ZSTD,
  sign_up_email               VARCHAR(256) ENCODE ZSTD,
  sign_up_company             VARCHAR(256) ENCODE ZSTD,
  sign_up_service_type        VARCHAR(64) ENCODE ZSTD,
  demo_request_company        VARCHAR(255) ENCODE ZSTD,
  demo_request_email          VARCHAR(255) ENCODE ZSTD,
  demo_request_insights       BOOLEAN ENCODE ZSTD,
  page_view_id                CHAR(36) ENCODE ZSTD,
  alias_user_id               varCHAR(255) ENCODE ZSTD
)
DISTSTYLE KEY
DISTKEY (event_id)
SORTKEY (collector_tstamp);

CREATE TABLE IF NOT EXISTS {{.output_schema}}.user_stitching{{.entropy}} (
  domain_userid,
  user_id,
  first_seen_tstamp
);
DISTSTYLE KEY
DISTKEY (domain_userid)
SORTKEY (first_seen_tstamp);

